name: market_my_house
description: Buy, sell and rent property.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_tags: ^0.3.0
  
  cloud_firestore: ^0.8.2+3
  firebase_core: ^0.2.5
  firebase_storage: ^1.1.0+1
  
  image_picker: ^0.4.12+1

  carousel_pro: ^0.0.1
  intl: ^0.15.8

  google_maps_flutter: ^0.5.7
  location: 1.4.1
  geoflutterfire: 1.0.2
  flutter_calendar_carousel: ^1.3.16


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
      uses-material-design: true
      assets:
        - logo.png
        - no_img.png
      fonts:
        - family: Montserrat
          fonts:
            - asset: fonts/Montserrat-Regular.ttf
        - family: Roboto
          fonts:
            - asset: fonts/Roboto-Regular.ttf
